# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         qpsmtpd
version:      0.40
version_from: lib/Qpsmtpd.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Temp:                    0
    Mail::Header:                  0
    MIME::Base64:                  0
    Net::DNS:                      0.39
    Time::HiRes:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
