--- #YAML:1.0
name:               qpsmtpd
version:            0.84
abstract:           Flexible smtpd daemon written in Perl
author:
    - Ask Bjoern Hansen <ask@develooper.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  0
    File::Temp:    0
    Mail::Header:  0
    MIME::Base64:  0
    Net::DNS:      0.39
    Net::IP:       0
    Time::HiRes:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
